import json
import os
import platform_conf
import stat
import sys

class VRManifest():
    def __init__(self):
        # Unique app ID
        # WARNING: Changing this may leave duplicate/broken VR manifest files around
        self.vrmanifest_app_key = "com.hapticpancake"
        # Get app and manifest paths
        # See https://pyinstaller.org/en/stable/runtime-information.html
        self.app_path = sys.executable

        vrmanifest_file = self.vrmanifest_app_key + ".vrmanifest"
        self.vrmanifest_path = os.path.join(platform_conf.PATH_USER_DATA, vrmanifest_file)
        # NOTE: OpenVR does not provide a way to remove manifest files by app_key
        # This path must not change when moving the bridge app, or SteamVR gets stuck!

        # Developer/unbundled launch path
        if self.is_windows:
            self.devlauncher_path = self.vrmanifest_path + ".devlaunch.bat"
        else:
            self.devlauncher_path = self.vrmanifest_path + ".devlaunch.sh"

        self.vrmanifest_recent = False

        self.vrmanifest_data = None
        self.prepare()

    @property
    def app_key(self):
        """Gets unique app ID for VR manifest"""
        return self.vrmanifest_app_key

    @property
    def is_app_bundled(self):
        """Gets if the app can be easily launched, e.g. as a PyInstaller bundle"""
        return getattr(sys, 'frozen', False)

    @property
    def is_recent(self):
        """Gets if VR manifest file has been saved this launch"""
        return self.vrmanifest_recent

    @property
    def is_windows(self):
        """Gets if the bridge app is running on Windows"""
        return sys.platform == "win32"

    @property
    def manifest_path(self):
        """Gets absolute path to VR manifest file"""
        return self.vrmanifest_path

    def prepare(self):
        """Prepare VR manifest data based on the current platform

        If bundled, uses app executable name in case it's been renamed.
        If unbundled, generates a launcher script (bat/sh) as a wrapper.
        """

        # VR manifest file distinguishes between Linux and Windows
        binary_path_type = "binary_path_linux"
        if self.is_windows:
            binary_path_type = "binary_path_windows"

        launch_path = self.app_path
        if not self.is_app_bundled:
            launch_path = self.devlauncher_path

        self.vrmanifest_data = {
            'applications': [{
                'app_key': self.app_key,
                binary_path_type: launch_path,
                'is_dashboard_overlay': True,
                'launch_type': "binary",
                'strings': {
                    'en_us': {
                        'description': "Bridge software to enable haptic feedback on trackers in VRChat and Resonite",
                        'name': "Haptic Pancake Bridge",
                    },
                },
            }],
            'source': "builtin",
        }

    def print_json(self):
        pretty_json = json.dumps(self.vrmanifest_data, ensure_ascii=False, sort_keys=True, indent=4)
        print(f"[VRManifest] VR manifest JSON data: \n---\n{pretty_json}\n---\n")

    def save_devlauncher(self):
        """Saves a dev-mode/unbundled launch script based on path"""
        if self.is_app_bundled:
            print(f"[VRManifest] Not saving dev-mode launch script, app is bundled")
            return

        print(f"[VRManifest] Also saving dev-mode launch script")

        # Try to use root of source repository, one folder from script path
        # This avoids dumping the config file into the Python venv
        # See https://stackoverflow.com/questions/9856683/using-pythons-os-path-how-do-i-go-up-one-directory
        app_main_script = os.path.abspath(sys.argv[0])
        app_dir = os.path.dirname(os.path.dirname(app_main_script))

        if self.is_windows:
            with open(self.devlauncher_path, 'w', encoding='utf-8') as launch_file:
                launch_file.writelines([
                    f"REM Generated by Haptic Pancake to let SteamVR launch the unbundled bridge app\n",
                    f"REM To avoid needing this file, build the bridge app using PyInstaller/etc\n",
                    f"\n",
                    f"cd /d \"{app_dir}\"\n",
                    f"\"{self.app_path}\" \"{app_main_script}\"\n",
                ])
                # See https://superuser.com/questions/135214/using-cd-command-in-windows-command-line-cant-navigate-to-d
        else:
            with open(self.devlauncher_path, 'w', encoding='utf-8') as launch_file:
                launch_file.writelines([
                    f"#!/bin/sh\n",
                    f"# Generated by Haptic Pancake to let SteamVR launch the unbundled bridge app\n",
                    f"# To avoid needing this file, build the bridge app using PyInstaller/etc\n",
                    f"\n",
                    f"cd \"{app_dir}\"\n",
                    f"\"{self.app_path}\" \"{app_main_script}\"\n",
                ])
            # Mark as executable on Linux
            # See https://stackoverflow.com/questions/12791997/how-do-you-do-a-simple-chmod-x-from-within-python
            launch_file_stat = os.stat(self.devlauncher_path)
            os.chmod(self.devlauncher_path, launch_file_stat.st_mode | stat.S_IXUSR)

    def remove_devlauncher(self):
        """Removes dev-mode/unbundled launch script"""
        try:
            os.remove(self.devlauncher_path)
            print(f"[VRManifest] Removed dev-mode launch script")
        except FileNotFoundError:
            pass

    def save(self):
        """Save generated VR manifest to file"""
        if not self.vrmanifest_data:
            raise ValueError("VR manifest JSON data is empty!  This should not happen")

        # Save file with pretty printing
        print(f"[VRManifest] Saving VR manifest: {self.manifest_path}")

        with open(self.vrmanifest_path, 'w', encoding='utf-8') as mvr_file:
            json.dump(self.vrmanifest_data, mvr_file, ensure_ascii=False, sort_keys=True, indent=4)

        # Save dev launcher if needed
        if not self.is_app_bundled:
            self.save_devlauncher()

        self.vrmanifest_recent = True

    def remove(self):
        """Remove generated VR manifest"""
        self.remove_devlauncher()

        try:
            os.remove(self.vrmanifest_path)
            print(f"[VRManifest] Removed VR manifest: {self.manifest_path}")
        except FileNotFoundError:
            pass

        self.vrmanifest_recent = True
